### ISSUE TITLE
potential bug in simulation.py

### ISSUE THREAD

**Issue by astronomyk** [oczoske/SpecCADO#1]
Servus. 

Nicht besonders wichtig zur Zeit - daher kein Email. 
Wollt das aber trotzdem dokumentieren, damit wir es nicht vergessen.

Line 149 in simulation.py, see ``image``:

    osample_y = np.int(image.shape[1] / nchiplines)

``image`` also appears in line 236

    XIMG_fpa[lower:upper, :] = image[J_IMG, I_IMG] * ijmask

Pycharm throws an error saying ``image`` is not defined.
Pycharm also notes that ``xilam_img`` from line 119 is never used and the line is therefore superfluous.

    xilam_img = xilam.image

Should ``image`` therefore actually be ``xilam_img``?

**Comment by oczoske** [comment]
That looks right. Nearest-pixel interpolation is legacy that should probably not be used anyway.
